# Generated by Django 4.2.16 on 2025-06-03 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=14)),
                ('aadhaar_file', models.FileField(upload_to='aadhaar_files/')),
                ('board', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=10)),
                ('stream', models.CharField(blank=True, max_length=30, null=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marksheet_file', models.FileField(upload_to='marksheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
