# Generated by Django 4.2.16 on 2025-06-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhaareducation',
            name='stream',
        ),
    ]
