# Generated by Django 4.2.16 on 2025-06-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_remove_aadhaareducation_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhaareducation',
            name='user',
        ),
    ]
